services: # Define the services to be run by Docker Compose
  db: # Name of the service, in this case, a PostgreSQL database
    image: postgres # Use the official PostgreSQL image from Docker Hub
    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container, allowing access to the database from the host
    volumes:
      - pgdata:/var/lib/postgresql/data # Mount a named volume 'pgdata' to persist data in the specified directory inside the container
    environment: # Set environment variables for the PostgreSQL container. These variables configure the PostgreSQL database.
      - POSTGRES_DB=dbname # The name of the database to be created
      - POSTGRES_USER=user # The username for the PostgreSQL database
      - POSTGRES_PASSWORD=pass # The password for the PostgreSQL database user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
volumes: # Define named volumes that can be used by services
  pgdata: # Named volume 'pgdata' used to persist PostgreSQL data outside the container